# Generated by Django 4.0.1 on 2022-01-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_blog_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=264, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=264, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
